# -*- coding: utf-8 -*-
"""
Created on Mon Jan 20 22:43:09 2020

@author: Balarka
"""

from nsepy.history import get_price_list


def NSE_TradedStocks(dateval):

    prices = get_price_list(dt=dateval)
    return prices['SYMBOL'].tolist()

def Nifty50():
    return ['ZEEL', 'GRASIM', 'NESTLEIND', 'TCS', 'ADANIPORTS', 'HCLTECH', 'INFY', 'SBIN', 
            'BHARTIARTL', 'YESBANK', 'TITAN', 'M&M', 'BAJAJFINSV', 'BAJFINANCE', 'RELIANCE',
            'EICHERMOT', 'TECHM', 'ITC', 'INFRATEL', 'HEROMOTOCO', 'SUNPHARMA', 'ULTRACEMCO', 
            'DRREDDY', 'HINDUNILVR', 'BRITANNIA', 'HDFCBANK', 'IOC', 'VEDL', 'WIPRO', 'TATASTEEL', 
            'JSWSTEEL', 'CIPLA', 'GAIL', 'LT', 'BAJAJ-AUTO', 'INDUSINDBK', 'HINDALCO', 'POWERGRID', 
            'AXISBANK', 'BPCL', 'ICICIBANK', 'HDFC', 'ASIANPAINT', 'KOTAKBANK', 'MARUTI', 'UPL', 
            'TATAMOTORS', 'NTPC', 'COALINDIA', 'ONGC']

def NiftyNext50():
    return ['ICICIPRULI', 'NHPC', 'INDIGO', 'ACC', 'HDFCLIFE', 'PFC', 'MCDOWELL-N', 'AMBUJACEM', 
            'PIDILITIND', 'AUROPHARMA', 'SBILIFE', 'DLF', 'CADILAHC', 'PAGEIND', 'MOTHERSUMI', 'OFSS', 
            'DABUR', 'DMART', 'NIACL', 'UBL', 'LUPIN', 'MARICO', 'SHREECEM', 'CONCOR', 'BANKBARODA', 
            'SIEMENS', 'PEL', 'BANDHANBNK', 'PGHH', 'BAJAJHLDNG', 'GODREJCP', 'HDFCAMC', 'COLPAL', 
            'ASHOKLEY', 'BIOCON', 'DIVISLAB', 'PNB', 'SRTRANSFIN', 'HINDZINC', 'ICICIGI', 'PETRONET', 
            'IBULHSGFIN', 'HINDPETRO', 'L&TFH', 'BERGEPAINT', 'BOSCHLTD', 'NMDC', 'HAVELLS', 'GICRE', 
            'IDEA']

def NiftySmallCap_250():
    return ['INDIAMART', 'PRSMJOHNSN', 'GRANULES', 'INTELLECT', 'CYIENT', 'SFL', 'DCAL', 'RELINFRA', 
            'ZENSARTECH', 'MINDAIND', 'RELCAPITAL', 'JINDALSAW', 'GSFC', 'GNFC', 'JCHAC', 'JUSTDIAL', 
            'DISHTV', 'EIDPARRY', 'ITDCEM', 'NIITTECH', 'ITDC', 'PRAJIND', 'CREDITACC', 'JBCHEPHARM', 
            'JYOTHYLAB', 'CARERATING', 'VAIBHAVGBL', 'DHFL', 'HEIDELBERG', 'GARFIBRES', 'PERSISTENT', 
            'RITES', 'INDOSTAR', 'BSOFT', 'JAGRAN', 'DELTACORP', 'PTC', 'KIRLOSENG', 'TCIEXP', 'RCF', 
            'AMBER', 'WESTLIFE', 'TIMKEN', 'THYROCARE', 'RVNL', 'ALLCARGO', 'OMAXE', 'KPRMILL', 
            'KAJARIACER', 'STAR', 'FSL', 'ASTERDM', 'BRIGADE', 'JKCEMENT', 'NILKAMAL', 'CERA', 'TRIDENT', 
            'CAPLIPOINT', 'HSCL', 'ITI', 'TCNSBRANDS', 'ZYDUSWELL', 'ORIENTELEC', 'DBL', 'KSCL', 'ICRA', 
            'BDL', 'VRLLOG', 'AEGISCHEM', 'JKTYRE', 'DEEPAKNTR', 'RESPONIND', 'FINEORG', 'INFIBEAM', 
            'NFL', 'TAKE', 'BALRAMCHIN', 'LAKSHVILAS', 'HERITGFOOD', 'VAKRANGEE', 'ORIENTREF', 'HFCL',
            'RADICO', 'TECHNOE', 'TATAELXSI', 'ELGIEQUIP', 'JKLAKSHMI', 'BAJAJCON', 'JSLHISAR', 
            'MAHSCOOTER', 'CENTURYPLY', 'TIINDIA', 'PGHL', 'TIMETECHNO', 'BASF', 'GRINDWELL', 
            'ASAHIINDIA', 'DIXON', 'IFCI', 'TATASTLBSL', 'SUZLON', 'ARVINDFASN', 'FINPIPE', 'CARBORUNIV', 
            'TATAINVEST', 'SONATSOFTW', 'APLAPOLLO', 'SIS', 'KALPATPOWR', 'INOXLEISUR', 'GMDCLTD', 
            'JSL', 'MINDACORP', 'UFLEX', 'IRCON', 'IDFC', 'TVTODAY', 'BALMLAWRIE', 'SWANENERGY', 
            'BLUESTARCO', 'WELSPUNIND', 'GULFOILLUB', 'MIDHANI', 'MHRIL', 'TV18BRDCST', 'AVANTIFEED', 
            'CDSL', 'AKZOINDIA', 'ESSELPACK', 'SUPRAJIT', 'TRITURBINE', 'NAVINFLUOR', 'J&KBANK', 
            'GODFRYPHLP', 'DCBBANK', 'BEML', 'INDIACEM', 'EQUITAS', 'NH', 'KTKBANK', 'PCJEWELLER', 
            'VIPIND', 'LAXMIMACH', 'MAGMA', 'RATNAMANI', 'NETWORK18', 'JAMNAAUTO', 'CEATLTD', 
            'HINDCOPPER', 'CANFINHOME', 'KEI', 'UJJIVAN', 'MAHSEAMLES', 'KOLTEPATIL', 'CGCL', 
            'PHILIPCARB', 'ORIENTCEM', 'SOBHA', 'SOUTHBANK', 'ASTRAZEN', 'PARAGMILK', 'FDC', 
            'JKPAPER', 'GET&D', 'AFFLE', 'LAURUSLABS', 'KPITTECH', 'MCX', 'CHAMBLFERT', 'BLISSGVS', 
            'METROPOLIS', 'VTL', 'WELCORP', 'VMART', 'PVR', 'SPANDANA', 'COCHINSHIP', 'NBVENTURES', 
            'GHCL', 'SHILPAMED', 'RAYMOND', 'VENKEYS', 'BAJAJELEC', 'NCC', 'SHK', 'GALAXYSURF', 
            'BOMDYEING', 'WABAG', 'GUJALKALI', 'STARCEMENT', 'PNCINFRA', 'ADVENZYMES', 'REDINGTON', 
            'WOCKPHARMA', 'FINCABLES', 'TEAMLEASE', 'DCMSHRIRAM', 'CCL', 'RAIN', 'KENNAMET', 'GREAVESCOT', 
            'MMTC', 'RALLIS', 'SADBHAV', 'NESCO', 'HIMATSEIDE', 'BIRLACORPN', 'GEPIL', 'LUXIND', 'FLFL', 
            'ECLERX', 'IFBIND', 'FMGOETZE', 'JMFINANCIL', 'SUNCLAYLTD', 'GESHIP', 'DBCORP', 'BSE', 'MOIL', 
            'LINDEINDIA', 'JISLJALEQS', 'MAHLOG', 'SUDARSCHEM', 'SPARC', 'GPPL', 'ADANIGREEN', 'IEX', 
            'KEC', 'MASFIN', 'CHALET', 'GAYAPROJ', 'IBULISL', 'KNRCON', 'LEMONTREE', 'JAICORPLTD', 
            'RENUKA', 'KARURVYSYA', 'ASHOKA', 'IRB', 'IIFL', 'SHOPERSTOP', 'CHENNPETRO', 'SPICEJET', 
            'REPCOHOME', 'SUNTECK', 'VSTIND', 'IBREALEST', 'RPOWER', 'MAHABANK', 'TASTYBITE']
    
if __name__ == '__main__':
    
    NSE_TradedStocks('20-01-2020')
    
    

